//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.07 at 12:46:22 PM CST 
//


package esg.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trustedCAs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pkiCA" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="openIdCA" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trustedServices">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="openIdIdentityProvider" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="gateway" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="baseSecureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="administratorPersonal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="administratorEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="myproxy">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="attributeService">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="authorizationService">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="oaiRepository">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="identityProvider">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="datanode" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="threddsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gridftpURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="versionDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trustedCAs",
    "trustedServices"
})
@XmlRootElement(name = "esgWhitelist")
public class EsgWhitelist {

    @XmlElement(required = true)
    protected EsgWhitelist.TrustedCAs trustedCAs;
    @XmlElement(required = true)
    protected EsgWhitelist.TrustedServices trustedServices;
    @XmlAttribute
    protected Integer versionDate;

    /**
     * Gets the value of the trustedCAs property.
     * 
     * @return
     *     possible object is
     *     {@link EsgWhitelist.TrustedCAs }
     *     
     */
    public EsgWhitelist.TrustedCAs getTrustedCAs() {
        return trustedCAs;
    }

    /**
     * Sets the value of the trustedCAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EsgWhitelist.TrustedCAs }
     *     
     */
    public void setTrustedCAs(EsgWhitelist.TrustedCAs value) {
        this.trustedCAs = value;
    }

    /**
     * Gets the value of the trustedServices property.
     * 
     * @return
     *     possible object is
     *     {@link EsgWhitelist.TrustedServices }
     *     
     */
    public EsgWhitelist.TrustedServices getTrustedServices() {
        return trustedServices;
    }

    /**
     * Sets the value of the trustedServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link EsgWhitelist.TrustedServices }
     *     
     */
    public void setTrustedServices(EsgWhitelist.TrustedServices value) {
        this.trustedServices = value;
    }

    /**
     * Gets the value of the versionDate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersionDate() {
        return versionDate;
    }

    /**
     * Sets the value of the versionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersionDate(Integer value) {
        this.versionDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pkiCA" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="openIdCA" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pkiCA",
        "openIdCA"
    })
    public static class TrustedCAs {

        @XmlElement(required = true)
        protected List<EsgWhitelist.TrustedCAs.PkiCA> pkiCA;
        @XmlElement(required = true)
        protected List<EsgWhitelist.TrustedCAs.OpenIdCA> openIdCA;

        /**
         * Gets the value of the pkiCA property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pkiCA property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPkiCA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EsgWhitelist.TrustedCAs.PkiCA }
         * 
         * 
         */
        public List<EsgWhitelist.TrustedCAs.PkiCA> getPkiCA() {
            if (pkiCA == null) {
                pkiCA = new ArrayList<EsgWhitelist.TrustedCAs.PkiCA>();
            }
            return this.pkiCA;
        }

        /**
         * Gets the value of the openIdCA property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the openIdCA property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOpenIdCA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EsgWhitelist.TrustedCAs.OpenIdCA }
         * 
         * 
         */
        public List<EsgWhitelist.TrustedCAs.OpenIdCA> getOpenIdCA() {
            if (openIdCA == null) {
                openIdCA = new ArrayList<EsgWhitelist.TrustedCAs.OpenIdCA>();
            }
            return this.openIdCA;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hash",
            "dn"
        })
        public static class OpenIdCA {

            @XmlElement(required = true)
            protected String hash;
            @XmlElement(required = true)
            protected String dn;

            /**
             * Gets the value of the hash property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHash() {
                return hash;
            }

            /**
             * Sets the value of the hash property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHash(String value) {
                this.hash = value;
            }

            /**
             * Gets the value of the dn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDn() {
                return dn;
            }

            /**
             * Sets the value of the dn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDn(String value) {
                this.dn = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hash",
            "dn"
        })
        public static class PkiCA {

            @XmlElement(required = true)
            protected String hash;
            @XmlElement(required = true)
            protected String dn;

            /**
             * Gets the value of the hash property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHash() {
                return hash;
            }

            /**
             * Sets the value of the hash property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHash(String value) {
                this.hash = value;
            }

            /**
             * Gets the value of the dn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDn() {
                return dn;
            }

            /**
             * Sets the value of the dn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDn(String value) {
                this.dn = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="openIdIdentityProvider" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="gateway" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="baseSecureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="administratorPersonal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="administratorEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="myproxy">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="attributeService">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="authorizationService">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="oaiRepository">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="identityProvider">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="datanode" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="threddsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gridftpURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "openIdIdentityProvider",
        "gateway",
        "datanode"
    })
    public static class TrustedServices {

        @XmlElement(required = true)
        protected List<EsgWhitelist.TrustedServices.OpenIdIdentityProvider> openIdIdentityProvider;
        @XmlElement(required = true)
        protected List<EsgWhitelist.TrustedServices.Gateway> gateway;
        @XmlElement(required = true)
        protected List<EsgWhitelist.TrustedServices.Datanode> datanode;

        /**
         * Gets the value of the openIdIdentityProvider property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the openIdIdentityProvider property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOpenIdIdentityProvider().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EsgWhitelist.TrustedServices.OpenIdIdentityProvider }
         * 
         * 
         */
        public List<EsgWhitelist.TrustedServices.OpenIdIdentityProvider> getOpenIdIdentityProvider() {
            if (openIdIdentityProvider == null) {
                openIdIdentityProvider = new ArrayList<EsgWhitelist.TrustedServices.OpenIdIdentityProvider>();
            }
            return this.openIdIdentityProvider;
        }

        /**
         * Gets the value of the gateway property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gateway property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGateway().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EsgWhitelist.TrustedServices.Gateway }
         * 
         * 
         */
        public List<EsgWhitelist.TrustedServices.Gateway> getGateway() {
            if (gateway == null) {
                gateway = new ArrayList<EsgWhitelist.TrustedServices.Gateway>();
            }
            return this.gateway;
        }

        /**
         * Gets the value of the datanode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datanode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatanode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EsgWhitelist.TrustedServices.Datanode }
         * 
         * 
         */
        public List<EsgWhitelist.TrustedServices.Datanode> getDatanode() {
            if (datanode == null) {
                datanode = new ArrayList<EsgWhitelist.TrustedServices.Datanode>();
            }
            return this.datanode;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="threddsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gridftpURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "organization",
            "commonName",
            "threddsURL",
            "gridftpURL"
        })
        public static class Datanode {

            @XmlElement(required = true)
            protected String organization;
            @XmlElement(required = true)
            protected String commonName;
            @XmlElement(required = true)
            protected String threddsURL;
            @XmlElement(required = true)
            protected String gridftpURL;

            /**
             * Gets the value of the organization property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrganization() {
                return organization;
            }

            /**
             * Sets the value of the organization property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrganization(String value) {
                this.organization = value;
            }

            /**
             * Gets the value of the commonName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCommonName() {
                return commonName;
            }

            /**
             * Sets the value of the commonName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCommonName(String value) {
                this.commonName = value;
            }

            /**
             * Gets the value of the threddsURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThreddsURL() {
                return threddsURL;
            }

            /**
             * Sets the value of the threddsURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThreddsURL(String value) {
                this.threddsURL = value;
            }

            /**
             * Gets the value of the gridftpURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGridftpURL() {
                return gridftpURL;
            }

            /**
             * Sets the value of the gridftpURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGridftpURL(String value) {
                this.gridftpURL = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="commonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="baseSecureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="identity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="administratorPersonal" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="administratorEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="myproxy">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="attributeService">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="authorizationService">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="oaiRepository">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="identityProvider">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "organization",
            "commonName",
            "hostname",
            "id",
            "description",
            "baseUrl",
            "baseSecureUrl",
            "identity",
            "administratorPersonal",
            "administratorEmail",
            "myproxy",
            "attributeService",
            "authorizationService",
            "oaiRepository",
            "identityProvider"
        })
        public static class Gateway {

            @XmlElement(required = true)
            protected String organization;
            @XmlElement(required = true)
            protected String commonName;
            @XmlElement(required = true)
            protected String hostname;
            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String baseUrl;
            @XmlElement(required = true)
            protected String baseSecureUrl;
            @XmlElement(required = true)
            protected String identity;
            @XmlElement(required = true)
            protected String administratorPersonal;
            @XmlElement(required = true)
            protected String administratorEmail;
            @XmlElement(required = true)
            protected EsgWhitelist.TrustedServices.Gateway.Myproxy myproxy;
            @XmlElement(required = true)
            protected EsgWhitelist.TrustedServices.Gateway.AttributeService attributeService;
            @XmlElement(required = true)
            protected EsgWhitelist.TrustedServices.Gateway.AuthorizationService authorizationService;
            @XmlElement(required = true)
            protected EsgWhitelist.TrustedServices.Gateway.OaiRepository oaiRepository;
            @XmlElement(required = true)
            protected EsgWhitelist.TrustedServices.Gateway.IdentityProvider identityProvider;

            /**
             * Gets the value of the organization property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrganization() {
                return organization;
            }

            /**
             * Sets the value of the organization property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrganization(String value) {
                this.organization = value;
            }

            /**
             * Gets the value of the commonName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCommonName() {
                return commonName;
            }

            /**
             * Sets the value of the commonName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCommonName(String value) {
                this.commonName = value;
            }

            /**
             * Gets the value of the hostname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostname() {
                return hostname;
            }

            /**
             * Sets the value of the hostname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostname(String value) {
                this.hostname = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the baseUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseUrl() {
                return baseUrl;
            }

            /**
             * Sets the value of the baseUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseUrl(String value) {
                this.baseUrl = value;
            }

            /**
             * Gets the value of the baseSecureUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseSecureUrl() {
                return baseSecureUrl;
            }

            /**
             * Sets the value of the baseSecureUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseSecureUrl(String value) {
                this.baseSecureUrl = value;
            }

            /**
             * Gets the value of the identity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentity() {
                return identity;
            }

            /**
             * Sets the value of the identity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentity(String value) {
                this.identity = value;
            }

            /**
             * Gets the value of the administratorPersonal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdministratorPersonal() {
                return administratorPersonal;
            }

            /**
             * Sets the value of the administratorPersonal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdministratorPersonal(String value) {
                this.administratorPersonal = value;
            }

            /**
             * Gets the value of the administratorEmail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdministratorEmail() {
                return administratorEmail;
            }

            /**
             * Sets the value of the administratorEmail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdministratorEmail(String value) {
                this.administratorEmail = value;
            }

            /**
             * Gets the value of the myproxy property.
             * 
             * @return
             *     possible object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.Myproxy }
             *     
             */
            public EsgWhitelist.TrustedServices.Gateway.Myproxy getMyproxy() {
                return myproxy;
            }

            /**
             * Sets the value of the myproxy property.
             * 
             * @param value
             *     allowed object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.Myproxy }
             *     
             */
            public void setMyproxy(EsgWhitelist.TrustedServices.Gateway.Myproxy value) {
                this.myproxy = value;
            }

            /**
             * Gets the value of the attributeService property.
             * 
             * @return
             *     possible object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.AttributeService }
             *     
             */
            public EsgWhitelist.TrustedServices.Gateway.AttributeService getAttributeService() {
                return attributeService;
            }

            /**
             * Sets the value of the attributeService property.
             * 
             * @param value
             *     allowed object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.AttributeService }
             *     
             */
            public void setAttributeService(EsgWhitelist.TrustedServices.Gateway.AttributeService value) {
                this.attributeService = value;
            }

            /**
             * Gets the value of the authorizationService property.
             * 
             * @return
             *     possible object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.AuthorizationService }
             *     
             */
            public EsgWhitelist.TrustedServices.Gateway.AuthorizationService getAuthorizationService() {
                return authorizationService;
            }

            /**
             * Sets the value of the authorizationService property.
             * 
             * @param value
             *     allowed object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.AuthorizationService }
             *     
             */
            public void setAuthorizationService(EsgWhitelist.TrustedServices.Gateway.AuthorizationService value) {
                this.authorizationService = value;
            }

            /**
             * Gets the value of the oaiRepository property.
             * 
             * @return
             *     possible object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.OaiRepository }
             *     
             */
            public EsgWhitelist.TrustedServices.Gateway.OaiRepository getOaiRepository() {
                return oaiRepository;
            }

            /**
             * Sets the value of the oaiRepository property.
             * 
             * @param value
             *     allowed object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.OaiRepository }
             *     
             */
            public void setOaiRepository(EsgWhitelist.TrustedServices.Gateway.OaiRepository value) {
                this.oaiRepository = value;
            }

            /**
             * Gets the value of the identityProvider property.
             * 
             * @return
             *     possible object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.IdentityProvider }
             *     
             */
            public EsgWhitelist.TrustedServices.Gateway.IdentityProvider getIdentityProvider() {
                return identityProvider;
            }

            /**
             * Sets the value of the identityProvider property.
             * 
             * @param value
             *     allowed object is
             *     {@link EsgWhitelist.TrustedServices.Gateway.IdentityProvider }
             *     
             */
            public void setIdentityProvider(EsgWhitelist.TrustedServices.Gateway.IdentityProvider value) {
                this.identityProvider = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AttributeService {

                @XmlAttribute
                protected String url;
                @XmlAttribute(name = "AuthorizationAuthority")
                protected String authorizationAuthority;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the authorizationAuthority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthorizationAuthority() {
                    return authorizationAuthority;
                }

                /**
                 * Sets the value of the authorizationAuthority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthorizationAuthority(String value) {
                    this.authorizationAuthority = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AuthorizationService {

                @XmlAttribute
                protected String url;
                @XmlAttribute(name = "AuthorizationAuthority")
                protected String authorizationAuthority;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the authorizationAuthority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthorizationAuthority() {
                    return authorizationAuthority;
                }

                /**
                 * Sets the value of the authorizationAuthority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthorizationAuthority(String value) {
                    this.authorizationAuthority = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class IdentityProvider {

                @XmlAttribute
                protected String url;
                @XmlAttribute(name = "AuthorizationAuthority")
                protected String authorizationAuthority;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the authorizationAuthority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthorizationAuthority() {
                    return authorizationAuthority;
                }

                /**
                 * Sets the value of the authorizationAuthority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthorizationAuthority(String value) {
                    this.authorizationAuthority = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Myproxy {

                @XmlAttribute
                protected Integer port;
                @XmlAttribute(name = "AuthorizationAuthority")
                protected String authorizationAuthority;

                /**
                 * Gets the value of the port property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getPort() {
                    return port;
                }

                /**
                 * Sets the value of the port property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setPort(Integer value) {
                    this.port = value;
                }

                /**
                 * Gets the value of the authorizationAuthority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthorizationAuthority() {
                    return authorizationAuthority;
                }

                /**
                 * Sets the value of the authorizationAuthority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthorizationAuthority(String value) {
                    this.authorizationAuthority = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="AuthorizationAuthority" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class OaiRepository {

                @XmlAttribute
                protected String url;
                @XmlAttribute(name = "AuthorizationAuthority")
                protected String authorizationAuthority;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the authorizationAuthority property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAuthorizationAuthority() {
                    return authorizationAuthority;
                }

                /**
                 * Sets the value of the authorizationAuthority property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAuthorizationAuthority(String value) {
                    this.authorizationAuthority = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "organization",
            "url"
        })
        public static class OpenIdIdentityProvider {

            @XmlElement(required = true)
            protected String organization;
            @XmlElement(required = true)
            protected String url;

            /**
             * Gets the value of the organization property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrganization() {
                return organization;
            }

            /**
             * Sets the value of the organization property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrganization(String value) {
                this.organization = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }

    }

}
