/*******************************************************************************
 * Copyright (c) 2011 Earth System Grid Federation
 * ALL RIGHTS RESERVED. 
 * U.S. Government sponsorship acknowledged.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * 
 * Neither the name of the <ORGANIZATION> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.07 at 12:46:22 PM CST 
//


package esg.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the esg.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: esg.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway.AuthorizationService }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway.AuthorizationService createEsgWhitelistTrustedServicesGatewayAuthorizationService() {
        return new EsgWhitelist.TrustedServices.Gateway.AuthorizationService();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway.OaiRepository }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway.OaiRepository createEsgWhitelistTrustedServicesGatewayOaiRepository() {
        return new EsgWhitelist.TrustedServices.Gateway.OaiRepository();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices }
     * 
     */
    public EsgWhitelist.TrustedServices createEsgWhitelistTrustedServices() {
        return new EsgWhitelist.TrustedServices();
    }

    /**
     * Create an instance of {@link EsgWhitelist }
     * 
     */
    public EsgWhitelist createEsgWhitelist() {
        return new EsgWhitelist();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedCAs.PkiCA }
     * 
     */
    public EsgWhitelist.TrustedCAs.PkiCA createEsgWhitelistTrustedCAsPkiCA() {
        return new EsgWhitelist.TrustedCAs.PkiCA();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Datanode }
     * 
     */
    public EsgWhitelist.TrustedServices.Datanode createEsgWhitelistTrustedServicesDatanode() {
        return new EsgWhitelist.TrustedServices.Datanode();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.OpenIdIdentityProvider }
     * 
     */
    public EsgWhitelist.TrustedServices.OpenIdIdentityProvider createEsgWhitelistTrustedServicesOpenIdIdentityProvider() {
        return new EsgWhitelist.TrustedServices.OpenIdIdentityProvider();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedCAs }
     * 
     */
    public EsgWhitelist.TrustedCAs createEsgWhitelistTrustedCAs() {
        return new EsgWhitelist.TrustedCAs();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway.IdentityProvider }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway.IdentityProvider createEsgWhitelistTrustedServicesGatewayIdentityProvider() {
        return new EsgWhitelist.TrustedServices.Gateway.IdentityProvider();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway createEsgWhitelistTrustedServicesGateway() {
        return new EsgWhitelist.TrustedServices.Gateway();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedCAs.OpenIdCA }
     * 
     */
    public EsgWhitelist.TrustedCAs.OpenIdCA createEsgWhitelistTrustedCAsOpenIdCA() {
        return new EsgWhitelist.TrustedCAs.OpenIdCA();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway.Myproxy }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway.Myproxy createEsgWhitelistTrustedServicesGatewayMyproxy() {
        return new EsgWhitelist.TrustedServices.Gateway.Myproxy();
    }

    /**
     * Create an instance of {@link EsgWhitelist.TrustedServices.Gateway.AttributeService }
     * 
     */
    public EsgWhitelist.TrustedServices.Gateway.AttributeService createEsgWhitelistTrustedServicesGatewayAttributeService() {
        return new EsgWhitelist.TrustedServices.Gateway.AttributeService();
    }

}
